#!/usr/bin/env python3
"""
Data preparation for Auto-VLM.
Downloads COCO val2017, builds tokenizer, creates multi-task training examples.

DO NOT EDIT THIS FILE — it is fixed infrastructure.
"""

import json
import os
import re
import zipfile
from collections import Counter
from pathlib import Path

import numpy as np
import requests
from PIL import Image

# ─── Constants ───────────────────────────────────────────────────────────────

DATA_DIR = Path("data")
IMAGE_DIR = DATA_DIR / "images" / "val2017"
ANN_DIR = DATA_DIR / "annotations"
PROCESSED_DIR = DATA_DIR / "processed"

IMAGE_SIZE = 224
NUM_LOC_TOKENS = 1000  # <loc000> to <loc999>
VOCAB_SIZE = 4000  # word-level tokens (on top of special + location tokens)
TRAIN_SPLIT = 4000
VAL_SPLIT = 1000

COCO_IMAGES_URL = "http://images.cocodataset.org/zips/val2017.zip"
COCO_ANN_URL = "http://images.cocodataset.org/annotations/annotations_trainval2017.zip"

# ─── Special Tokens ─────────────────────────────────────────────────────────

PAD_TOKEN = "<pad>"
BOS_TOKEN = "<bos>"
EOS_TOKEN = "<eos>"
UNK_TOKEN = "<unk>"
SEP_TOKEN = "<sep>"
CAPTION_TOKEN = "<caption>"
VQA_TOKEN = "<vqa>"
OD_TOKEN = "<od>"
SEG_TOKEN = "<seg>"
DESCRIBE_TOKEN = "<describe>"

SPECIAL_TOKENS = [
    PAD_TOKEN, BOS_TOKEN, EOS_TOKEN, UNK_TOKEN, SEP_TOKEN,
    CAPTION_TOKEN, VQA_TOKEN, OD_TOKEN, SEG_TOKEN, DESCRIBE_TOKEN,
]
NUM_SPECIAL = len(SPECIAL_TOKENS)

# Location tokens: <loc000> to <loc999>
LOC_TOKENS = [f"<loc{i:03d}>" for i in range(NUM_LOC_TOKENS)]


# ─── Tokenizer ──────────────────────────────────────────────────────────────

class SimpleTokenizer:
    """Word-level tokenizer with special and location tokens."""

    def __init__(self):
        self.token_to_id = {}
        self.id_to_token = {}
        self.vocab_size = 0

    def build(self, texts, max_words=VOCAB_SIZE):
        """Build vocabulary from texts."""
        # Start with special tokens
        all_tokens = list(SPECIAL_TOKENS) + list(LOC_TOKENS)

        # Count words
        counter = Counter()
        for text in texts:
            words = self._tokenize_text(text)
            counter.update(words)

        # Add most common words
        for word, _ in counter.most_common(max_words):
            if word not in all_tokens:
                all_tokens.append(word)

        # Build mappings
        self.token_to_id = {t: i for i, t in enumerate(all_tokens)}
        self.id_to_token = {i: t for i, t in enumerate(all_tokens)}
        self.vocab_size = len(all_tokens)
        print(f"Tokenizer built: {self.vocab_size} tokens "
              f"({NUM_SPECIAL} special + {NUM_LOC_TOKENS} location + "
              f"{self.vocab_size - NUM_SPECIAL - NUM_LOC_TOKENS} words)")

    def encode(self, text):
        """Encode text to token IDs."""
        if isinstance(text, list):
            # Already tokenized (list of token strings)
            return [self.token_to_id.get(t, self.token_to_id[UNK_TOKEN]) for t in text]

        words = self._tokenize_text(text)
        ids = []
        for w in words:
            if w in self.token_to_id:
                ids.append(self.token_to_id[w])
            else:
                # Character fallback for unknown words
                for ch in w:
                    ids.append(self.token_to_id.get(ch, self.token_to_id[UNK_TOKEN]))
        return ids

    def decode(self, ids):
        """Decode token IDs to text."""
        tokens = [self.id_to_token.get(i, UNK_TOKEN) for i in ids]
        # Join with spaces, clean up
        text = " ".join(tokens)
        # Remove spaces before punctuation
        text = re.sub(r'\s+([.,!?;:])', r'\1', text)
        return text

    def save(self, path):
        """Save tokenizer to JSON."""
        data = {
            "token_to_id": self.token_to_id,
            "vocab_size": self.vocab_size,
        }
        with open(path, "w") as f:
            json.dump(data, f)

    def load(self, path):
        """Load tokenizer from JSON."""
        with open(path) as f:
            data = json.load(f)
        self.token_to_id = data["token_to_id"]
        self.id_to_token = {int(i): t for t, i in self.token_to_id.items()}
        # Also add string keys
        self.id_to_token.update({i: t for t, i in self.token_to_id.items()
                                  if isinstance(i, int)})
        # Rebuild id_to_token properly
        self.id_to_token = {v: k for k, v in self.token_to_id.items()}
        self.vocab_size = data["vocab_size"]

    @staticmethod
    def _tokenize_text(text):
        """Simple word tokenization: lowercase, split on whitespace and punctuation."""
        text = text.lower().strip()
        # Add spaces around punctuation
        text = re.sub(r'([.,!?;:\'\"()\[\]{}])', r' \1 ', text)
        # Split and filter empty
        return [w for w in text.split() if w]


# ─── Coordinate Encoding ────────────────────────────────────────────────────

def coord_to_token(val, img_dim):
    """Convert a coordinate value to a location token string."""
    normalized = max(0, min(val / img_dim, 1.0))
    bin_idx = int(normalized * (NUM_LOC_TOKENS - 1))
    return f"<loc{bin_idx:03d}>"


def bbox_to_tokens(bbox, img_w, img_h):
    """Convert COCO bbox [x, y, w, h] to 4 location tokens [x1, y1, x2, y2]."""
    x, y, w, h = bbox
    return [
        coord_to_token(x, img_w),
        coord_to_token(y, img_h),
        coord_to_token(x + w, img_w),
        coord_to_token(y + h, img_h),
    ]


def polygon_to_tokens(segmentation, img_w, img_h, max_vertices=16):
    """Convert COCO polygon to location tokens, subsampled to max_vertices."""
    if not segmentation or not segmentation[0]:
        return []
    # Take the largest polygon
    poly = max(segmentation, key=len)
    # poly is [x1, y1, x2, y2, ...] flat list
    points = [(poly[i], poly[i + 1]) for i in range(0, len(poly), 2)]

    # Subsample if too many points
    if len(points) > max_vertices:
        indices = np.linspace(0, len(points) - 1, max_vertices, dtype=int)
        points = [points[i] for i in indices]

    tokens = []
    for x, y in points:
        tokens.append(coord_to_token(x, img_w))
        tokens.append(coord_to_token(y, img_h))
    return tokens


# ─── Download Helpers ────────────────────────────────────────────────────────

def download_file(url, dest_path):
    """Download a file with progress."""
    if dest_path.exists():
        print(f"  Already exists: {dest_path}")
        return
    dest_path.parent.mkdir(parents=True, exist_ok=True)
    print(f"  Downloading {url}...")
    response = requests.get(url, stream=True)
    response.raise_for_status()
    total = int(response.headers.get("content-length", 0))
    downloaded = 0
    with open(dest_path, "wb") as f:
        for chunk in response.iter_content(chunk_size=8192):
            f.write(chunk)
            downloaded += len(chunk)
            if total > 0:
                pct = downloaded / total * 100
                print(f"\r  {pct:.1f}% ({downloaded // 1024 // 1024}MB / {total // 1024 // 1024}MB)", end="", flush=True)
    print()


def download_coco():
    """Download COCO val2017 images and annotations."""
    print("=== Downloading COCO val2017 ===")

    # Images
    images_zip = DATA_DIR / "val2017.zip"
    download_file(COCO_IMAGES_URL, images_zip)
    if not IMAGE_DIR.exists():
        print("  Extracting images...")
        with zipfile.ZipFile(images_zip) as zf:
            zf.extractall(DATA_DIR / "images")

    # Annotations
    ann_zip = DATA_DIR / "annotations.zip"
    download_file(COCO_ANN_URL, ann_zip)
    if not (ANN_DIR / "captions_val2017.json").exists():
        print("  Extracting annotations...")
        with zipfile.ZipFile(ann_zip) as zf:
            # Only extract val annotations
            for name in zf.namelist():
                if "val2017" in name:
                    zf.extract(name, DATA_DIR)

    print("  COCO data ready.")


# ─── Image Preprocessing ────────────────────────────────────────────────────

def preprocess_images(image_ids, id_to_filename):
    """Load, resize, and normalize images. Returns dict of image_id -> numpy array."""
    cache_path = PROCESSED_DIR / "images.npz"
    if cache_path.exists():
        print("  Loading cached images...")
        data = np.load(cache_path)
        images = {int(k): data[k] for k in data.files}
        print(f"  Loaded {len(images)} images from cache.")
        return images

    print(f"  Processing {len(image_ids)} images to {IMAGE_SIZE}x{IMAGE_SIZE}...")
    images = {}
    for i, img_id in enumerate(image_ids):
        fname = id_to_filename[img_id]
        img_path = IMAGE_DIR / fname
        try:
            img = Image.open(img_path).convert("RGB")
            img = img.resize((IMAGE_SIZE, IMAGE_SIZE), Image.BILINEAR)
            arr = np.array(img, dtype=np.float32) / 255.0  # [0, 1]
            images[img_id] = arr
        except Exception as e:
            print(f"  Warning: failed to load {img_path}: {e}")
            continue
        if (i + 1) % 500 == 0:
            print(f"  Processed {i + 1}/{len(image_ids)} images")

    PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(cache_path, **{str(k): v for k, v in images.items()})
    print(f"  Saved {len(images)} images to cache.")
    return images


# ─── Task Example Generation ────────────────────────────────────────────────

def generate_caption_examples(captions_data):
    """Generate captioning task examples."""
    examples = []
    for ann in captions_data["annotations"]:
        examples.append({
            "image_id": ann["image_id"],
            "task": "caption",
            "input_tokens": [CAPTION_TOKEN],
            "target_text": ann["caption"].strip(),
        })
    return examples


def generate_od_examples(instances_data, id_to_cat):
    """Generate object detection task examples."""
    # Group annotations by image
    img_anns = {}
    for ann in instances_data["annotations"]:
        if ann.get("iscrowd", 0):
            continue
        img_id = ann["image_id"]
        if img_id not in img_anns:
            img_anns[img_id] = []
        img_anns[img_id].append(ann)

    # Get image dimensions
    img_dims = {img["id"]: (img["width"], img["height"])
                for img in instances_data["images"]}

    examples = []
    for img_id, anns in img_anns.items():
        if img_id not in img_dims:
            continue
        w, h = img_dims[img_id]
        target_tokens = []
        for ann in anns[:10]:  # Max 10 objects per image
            cat_name = id_to_cat[ann["category_id"]]
            box_tokens = bbox_to_tokens(ann["bbox"], w, h)
            if target_tokens:
                target_tokens.append(SEP_TOKEN)
            target_tokens.append(cat_name)
            target_tokens.extend(box_tokens)
        target_tokens.append(EOS_TOKEN)

        examples.append({
            "image_id": img_id,
            "task": "od",
            "input_tokens": [OD_TOKEN],
            "target_tokens_raw": target_tokens,
        })
    return examples


def generate_seg_examples(instances_data, id_to_cat):
    """Generate segmentation task examples."""
    img_anns = {}
    for ann in instances_data["annotations"]:
        if ann.get("iscrowd", 0):
            continue
        if not ann.get("segmentation"):
            continue
        if isinstance(ann["segmentation"], dict):
            continue  # Skip RLE format
        img_id = ann["image_id"]
        if img_id not in img_anns:
            img_anns[img_id] = []
        img_anns[img_id].append(ann)

    img_dims = {img["id"]: (img["width"], img["height"])
                for img in instances_data["images"]}

    examples = []
    for img_id, anns in img_anns.items():
        if img_id not in img_dims:
            continue
        w, h = img_dims[img_id]
        target_tokens = []
        for ann in anns[:5]:  # Max 5 objects (polygons are verbose)
            cat_name = id_to_cat[ann["category_id"]]
            poly_tokens = polygon_to_tokens(ann["segmentation"], w, h, max_vertices=12)
            if not poly_tokens:
                continue
            if target_tokens:
                target_tokens.append(SEP_TOKEN)
            target_tokens.append(cat_name)
            target_tokens.extend(poly_tokens)
        if not target_tokens:
            continue
        target_tokens.append(EOS_TOKEN)

        examples.append({
            "image_id": img_id,
            "task": "seg",
            "input_tokens": [SEG_TOKEN],
            "target_tokens_raw": target_tokens,
        })
    return examples


def generate_vqa_examples(instances_data, id_to_cat):
    """Generate VQA examples from COCO annotations."""
    img_anns = {}
    for ann in instances_data["annotations"]:
        if ann.get("iscrowd", 0):
            continue
        img_id = ann["image_id"]
        if img_id not in img_anns:
            img_anns[img_id] = []
        img_anns[img_id].append(ann)

    examples = []
    for img_id, anns in img_anns.items():
        cats = [id_to_cat[a["category_id"]] for a in anns]
        cat_counts = Counter(cats)
        unique_cats = list(cat_counts.keys())

        # Count question: "How many X are in the image?"
        for cat, count in cat_counts.items():
            examples.append({
                "image_id": img_id,
                "task": "vqa",
                "input_tokens": [VQA_TOKEN],
                "question": f"how many {cat} are in the image?",
                "answer": str(count),
            })

        # Existence question: "Is there a X in the image?"
        if unique_cats:
            cat = unique_cats[0]
            examples.append({
                "image_id": img_id,
                "task": "vqa",
                "input_tokens": [VQA_TOKEN],
                "question": f"is there a {cat} in the image?",
                "answer": "yes",
            })

        # "What objects are in the image?"
        examples.append({
            "image_id": img_id,
            "task": "vqa",
            "input_tokens": [VQA_TOKEN],
            "question": "what objects are in the image?",
            "answer": ", ".join(unique_cats[:5]),
        })

    return examples


def generate_describe_examples(captions_data):
    """Generate describe task examples by combining multiple captions."""
    # Group captions by image
    img_caps = {}
    for ann in captions_data["annotations"]:
        img_id = ann["image_id"]
        if img_id not in img_caps:
            img_caps[img_id] = []
        img_caps[img_id].append(ann["caption"].strip())

    examples = []
    for img_id, caps in img_caps.items():
        # Use the longest caption as the description
        desc = max(caps, key=len)
        examples.append({
            "image_id": img_id,
            "task": "describe",
            "input_tokens": [DESCRIBE_TOKEN],
            "target_text": desc,
        })
    return examples


# ─── Main Processing Pipeline ───────────────────────────────────────────────

def process_all():
    """Full data preparation pipeline."""
    PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

    # Check if already processed
    if (PROCESSED_DIR / "train.json").exists() and (PROCESSED_DIR / "tokenizer.json").exists():
        print("Data already processed. Delete data/processed/ to reprocess.")
        return

    # 1. Download COCO
    download_coco()

    # 2. Load annotations
    print("\n=== Loading annotations ===")
    with open(ANN_DIR / "captions_val2017.json") as f:
        captions_data = json.load(f)
    with open(ANN_DIR / "instances_val2017.json") as f:
        instances_data = json.load(f)

    # Category mapping
    id_to_cat = {cat["id"]: cat["name"] for cat in instances_data["categories"]}
    print(f"  {len(id_to_cat)} categories, "
          f"{len(instances_data['images'])} images, "
          f"{len(instances_data['annotations'])} instance annotations, "
          f"{len(captions_data['annotations'])} captions")

    # 3. Get all image IDs and metadata
    id_to_filename = {img["id"]: img["file_name"] for img in instances_data["images"]}
    all_image_ids = sorted(id_to_filename.keys())

    # 4. Train/val split (deterministic)
    rng = np.random.RandomState(42)
    rng.shuffle(all_image_ids)
    train_ids = set(all_image_ids[:TRAIN_SPLIT])
    val_ids = set(all_image_ids[TRAIN_SPLIT:TRAIN_SPLIT + VAL_SPLIT])
    print(f"  Split: {len(train_ids)} train, {len(val_ids)} val")

    # 5. Preprocess images
    print("\n=== Preprocessing images ===")
    all_ids = list(train_ids | val_ids)
    images = preprocess_images(all_ids, id_to_filename)

    # 6. Generate task examples
    print("\n=== Generating task examples ===")
    caption_examples = generate_caption_examples(captions_data)
    od_examples = generate_od_examples(instances_data, id_to_cat)
    seg_examples = generate_seg_examples(instances_data, id_to_cat)
    vqa_examples = generate_vqa_examples(instances_data, id_to_cat)
    describe_examples = generate_describe_examples(captions_data)

    print(f"  Captions: {len(caption_examples)}")
    print(f"  Object Detection: {len(od_examples)}")
    print(f"  Segmentation: {len(seg_examples)}")
    print(f"  VQA: {len(vqa_examples)}")
    print(f"  Describe: {len(describe_examples)}")

    all_examples = caption_examples + od_examples + seg_examples + vqa_examples + describe_examples

    # Filter to only images we have
    all_examples = [ex for ex in all_examples if ex["image_id"] in images]

    # 7. Build tokenizer from all text
    print("\n=== Building tokenizer ===")
    all_texts = []
    for ex in all_examples:
        if "target_text" in ex:
            all_texts.append(ex["target_text"])
        if "question" in ex:
            all_texts.append(ex["question"])
        if "answer" in ex:
            all_texts.append(ex["answer"])
    # Add category names
    all_texts.extend(id_to_cat.values())

    tokenizer = SimpleTokenizer()
    tokenizer.build(all_texts, max_words=VOCAB_SIZE)

    # 8. Tokenize all examples
    print("\n=== Tokenizing examples ===")
    processed_examples = []
    for ex in all_examples:
        img_id = ex["image_id"]
        task = ex["task"]

        if task in ("caption", "describe"):
            input_ids = tokenizer.encode(ex["input_tokens"])
            target_ids = tokenizer.encode(ex["target_text"]) + [tokenizer.token_to_id[EOS_TOKEN]]

        elif task == "vqa":
            q_tokens = tokenizer.encode(ex["question"])
            input_ids = tokenizer.encode(ex["input_tokens"]) + q_tokens + [tokenizer.token_to_id[SEP_TOKEN]]
            target_ids = tokenizer.encode(ex["answer"]) + [tokenizer.token_to_id[EOS_TOKEN]]

        elif task in ("od", "seg"):
            input_ids = tokenizer.encode(ex["input_tokens"])
            target_ids = tokenizer.encode(ex["target_tokens_raw"])

        else:
            continue

        # Skip very long sequences (>256 target tokens)
        if len(target_ids) > 256:
            continue

        processed_examples.append({
            "image_id": img_id,
            "task": task,
            "input_ids": input_ids,
            "target_ids": target_ids,
        })

    # 9. Split into train/val
    train_examples = [ex for ex in processed_examples if ex["image_id"] in train_ids]
    val_examples = [ex for ex in processed_examples if ex["image_id"] in val_ids]

    print(f"\n  Train examples: {len(train_examples)}")
    print(f"  Val examples: {len(val_examples)}")

    # Task distribution
    for split_name, split_data in [("train", train_examples), ("val", val_examples)]:
        task_counts = Counter(ex["task"] for ex in split_data)
        print(f"  {split_name}: {dict(task_counts)}")

    # 10. Save
    print("\n=== Saving processed data ===")
    tokenizer.save(PROCESSED_DIR / "tokenizer.json")

    with open(PROCESSED_DIR / "train.json", "w") as f:
        json.dump(train_examples, f)
    with open(PROCESSED_DIR / "val.json", "w") as f:
        json.dump(val_examples, f)

    # Save metadata
    meta = {
        "image_size": IMAGE_SIZE,
        "num_loc_tokens": NUM_LOC_TOKENS,
        "vocab_size": tokenizer.vocab_size,
        "num_train": len(train_examples),
        "num_val": len(val_examples),
        "categories": id_to_cat,
        "train_image_ids": sorted(train_ids),
        "val_image_ids": sorted(val_ids),
    }
    with open(PROCESSED_DIR / "meta.json", "w") as f:
        json.dump(meta, f, indent=2, default=int)

    print("\nData preparation complete!")
    print(f"  Tokenizer: {PROCESSED_DIR / 'tokenizer.json'}")
    print(f"  Train data: {PROCESSED_DIR / 'train.json'}")
    print(f"  Val data: {PROCESSED_DIR / 'val.json'}")
    print(f"  Images: {PROCESSED_DIR / 'images.npz'}")


# ─── Loading Helpers (used by train_mlx.py) ──────────────────────────────────

def load_tokenizer():
    """Load the pre-built tokenizer."""
    tok = SimpleTokenizer()
    tok.load(PROCESSED_DIR / "tokenizer.json")
    return tok


def load_data(split="train"):
    """Load processed examples for a split."""
    with open(PROCESSED_DIR / f"{split}.json") as f:
        return json.load(f)


def load_images():
    """Load preprocessed images as a dict of image_id -> numpy array."""
    data = np.load(PROCESSED_DIR / "images.npz")
    return {int(k): data[k] for k in data.files}


def load_metadata():
    """Load dataset metadata."""
    with open(PROCESSED_DIR / "meta.json") as f:
        return json.load(f)


if __name__ == "__main__":
    process_all()
